print("enter the vector1")
print("enter the vector2")
x1=int(input("enter x1"))
x2=int(input("enter x2")) 
x3=int(input("enter x3"))

y1=int(input("enter y1"))
y2=int(input("enter y2"))
y3=int(input("enter y3"))
print(x1*y1+x2*y2+x3*y3)
